CREATE TABLE SCHOOL
(
  SCHOOL_ID   INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(25)        NOT NULL,
  DESCRIPTION TEXT               NOT NULL
);

INSERT INTO SCHOOL (NAME, DESCRIPTION)
VALUES ('Hogeschool Utrecht', 'Great school!');


DROP TABLE STUDENTS;