CREATE TABLE COURSES
(
  COURSE_ID     INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(25)        NOT NULL,
  CATEGORY      VARCHAR(25)        NOT NULL,
  LOCATION      VARCHAR(25)        NOT NULL,
  DESCRIPTION   TEXT               NOT NULL
);


CREATE TABLE STUDENTS
(
  STUDENT_ID    INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(25)        NOT NULL,
  CATEGORY      VARCHAR(25)        NOT NULL,
  LOCATION      VARCHAR(25)        NOT NULL,
  STARTING_DATE VARCHAR(25)        NOT NULL,
  DESCRIPTION   TEXT               NOT NULL
);
CREATE TABLE SCHOOLS
(
  SCHOOL_ID INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(25)        NOT NULL,
  LOCATION  VARCHAR(25)        NOT NULL
);
INSERT INTO COURSES (NAME, CATEGORY, LOCATION, STARTING_DATE, DESCRIPTION)
VALUES ('Patterns and Frameworks', 'Java Programming', 'Nijenoord 1, Utrecht', '01-05-2016', 'Great course!');
